bigip_login_secret: f5-bigip-ctlr-login
rbac:
  create: true
serviceAccount:
  create: true
  name:
namespace: kube-system
args:
  bigip_url: 192.168.1.245
  bigip_partition: test
  log_level: INFO
  openshift_sdn_name: /test/vxlan-tunnel-mp
  pool_member_type: cluster
  insecure: true
  as3_validation: true
  manage_routes: true
  manage_ingress: false
  manage_configmaps: false
  route_vserver_addr: 10.10.10.11
image:
  user: f5networks
  repo: k8s-bigip-ctlr
  pullPolicy: Always
nodeSelector: {}
tolerations: []
livenessProbe: {}
readinessProbe: {}
resources: {}
version: latest